export default {
    success: "S",
    failed: 'F',
    na: "NA",
    apiSource: 'Mobile',
    pleaseTryAgainSomeTime: 'No response from server, please try again after sometime.',
    select: 'Select',
    nodataAvailable: "No Data Available",
    tail: "tail",
    userName: "Username",
    enterUserName: "Enter Username",
    userType: "User Type",
    countries: "Countries",
    states: 'States',
    required: "Required",
    selectDate: "Select Date",
    dateofBirth: "Date of Birth",
    submit: "Submit",
    cancel: 'Cancel',
    gender: "Gender",
    dashboard: 'Dashboard',
    goToNextPage: "Go to next page",
    clear: 'Clear',
    done: "Done",
    selected: ' Selected',
    placeHolderSearch: 'Search countries',
    placeHolderSearchState: 'Search states',
    placeHolderSearchCity: 'Search city',
    searchResult: "Search result",
    listofCountries: "List of countries",
    listofStates: "List of states",
    listofCity: "List of city",
    new: 'New',
    assigned: 'Assigned',
    inProcess: 'In Process',
    others: 'Others',
    converted: 'Converted',
    notInteres: 'Not Interest',
    notContactable: 'Not Contactable',
    closeCircle: 'closecircle',
    addLead: 'Add Lead',
    addOppertunity: 'Add Oppertunity',
    addActivity: 'Add activity',


    //icon Entypo

    chevronRight: 'chevron-right',
    chevronLeft: 'chevron-left',

    //Octicons
    circleSlash: 'circle-slash',

    //MaterialCommunityIcons

    dotsVertical: 'dots-vertical',
    clockFast: 'clock-fast',

    //Ionicons
    add: 'add',

    //AntDesign

    close: 'close',
    //EvilIcons
    chevronDown: "chevron-down",

    //months

    jan: 'Jan',
    feb: 'Feb',
    mar: 'Mar',
    apr: 'Apr',
    may: 'May',
    june: 'June',
    july: 'July',
    aug: 'Aug',
    sep: 'Sep',
    oct: 'Oct',
    nov: 'Nov',
    dec: 'Dec',

    //modal poup

    modalPopUpHeight: 165,
    modalPopUpWidth: '220rem',
    modalRadius: 5,
    modalM_Top: 550,
    modalM_Left: 100,
    modalP_Horizontal: 12,

    //leadPage

    rightContainerPadding: 5,
    leftContainerPadding: 4,
    p97: '97rem',
    p82: '82rem',
    pieTextSize: 23,
    pieTextContentPaddingLeft: 75,
    pieTextContentPaddingtop: 70,
    pieContainerPadding: 20,
    leadDataHeaderPadding: 15,
    noDataWidth: 390,
    noDataHeight: 140,
    elevation7: 7,
    bottomRadius: 3,
    leadDataCardBodyHeight: 190,
    leadDataCardBodyWidth: 390,
    leadDataCardHeadHeight: 55,
    leadDataCardHeadWidth: 390,
    verticleLineHeight: 30,
    verticleLineWidth: '1rem',

    //height 

    height3: '3rem',
    height5: '5rem',
    height10: '10rem',
    height15: '15rem',
    height20: '20rem',
    height23: '23rem',
    height25: '25rem',
    height30: '30rem',
    height40: '40rem',
    height45: '45rem',
    height50: '50rem',
    height55: '55rem',
    height60: '60rem',
    height70: '70rem',
    height80: '80rem',
    height90: '90rem',
    height100: '100rem',
    height120: '120rem',
    heigh100: '100rem',
    heigh130 : '130rem',
    height150: '150rem',
    height200: '200rem',
    height250: '250rem',
    height270: '270rem',
    height300: '300rem',
    height350: '350rem',
    height450: '450rem',
    height550: '550rem',
    height750: '750rem',

    //padding

    p35: "35rem",
    p45: "45rem",
    p65: "65rem",

    //margin
    m100: '100rem',
    m120: '120rem',
    m140: '140rem',
    m150: '150rem',
    m167: '167rem',
    m170: '170rem',
    m180: '180rem',
    m200: '200rem',
    m210: '210rem',
    m217: '217rem',
    m300: '300rem',


    //Bottom tab

    imageHeight: 30,
    imageWidth: 30,
    bottom: '15rem',
    borderRadius40: '40rem',
    dashBoard: 'Dashboard',
    leadClient: 'Lead/Client',
    oppertunities: 'Oppertunities',
    iconSize: '23rem',
    buttonWidth: '50rem',

    //modalPopUp
    marginTop: -75,
    marginLeft: -75,
    marginTop: -95,
    marginLeft: -95,

    //Activity
    saveActivity: 'Save Activity',
    activity: 'Activity',
    ActivityCreatedDate: 'Activity created date',
    SelfJoint: 'Self/Joint',
    InvitedBy: 'Invited By',
    searchBy: 'Search by prospect ID/ Name/Mobile',
    search1: 'search1',
    width5: '5%',
    width70: '70%',
    width90: '90%',
    width92: '92%',
    width94: '94%',
    width95: '95%',
    iconHeight: '30rem',
    iconWidth: '30rem',
    phoneCall: 'Phone Call',
    nonBusinessMeet: 'Non Business Meet',
    baveshKasppsadiya: 'Bavesh Kasppsadiya',
    smithaIyar: 'Smitha Iyar',
    nagadharBandi: 'Nagadhar Bandi',
    code: '48006800',
    ARCARECode: 'ARCC/ARCARE Code',
    careCode: '223462588',
    clientCode: 'Client Code',
    cCode: 'E97XXX',
    created: 'created',
    createdOn: 'May 14 2023, 10:20 AM',
    call9837432473: 'Call(9837432473)',
    message: 'Message',
    editActivity: 'Edit Activity',
    updateactivity: "Update Activity",
    outcome: 'Outcome',
    anandMishra: 'Anand Mishra(60020)',
    yogeshDhayfule: 'Yogesh Dhayafule(70008)',
    hours0: 0,
    hours4: 4,
    Add: 'Add',
    createdBy: 'Created By:',
    mobileNum: 'Mobile No:',

    privilege: 'Privilege',
    preferred: 'Preferred',
    hni: 'HNI',
    products: 'Products',
    actionType: 'Action Type',
    selectactionType: 'Select Action Type',
    invitee: 'Invitee',
    activityStatus: 'Activity Status : ',
    selectInvitee: 'Select Invitee',
    selecttActivityStatus: 'Select activity Status',
    selectAll: 'Select All',
    phoneCall: 'Phone Call',
    meeting: 'Meeting',
    anandSharma: 'Anand Sharma',
    amolMul: 'Amul Mul chandrakant',
    dixon: 'Dixon Dsouuza',


    //Lead Filter
    coldCall : 'cold Call',
    refferal : 'Referral',
    telecalling : 'Tele Calling',
    referral : 'Refferal',
    online  : 'Online',
    ofline : 'Offline',
    candT : 'C & T',
    potentialRevenueinlac : 'Potential Revenue (in Lacs)',
    AUM : 'AUM',
    //add activity

    addOutcome: 'Add Outcome',
    leadId: 'Lead id : ',
    enterOutCome: 'Enter Outcome',
    toSearch: 'Search To Find Lead or client',
    mobileNumber: 7634564545,
    activityDate: 'Activity Date',
    dateStructure: 'DD/MM/YYYY',
    duration:'Duration',
    hour0:'0 Hours',
    mins0:'0 Minutes',
    enterOutcomeForActivity:'Enter Outcome for the activity',
    producType:'Product Type',
    callOutCome:'Call Outcome',
    selectProduct:'Select Product',
    selectCallOutCome:'Select Call Outcome',
    nextScheduledDate:'Next shcheduled Date & Time',
    scheduledDateTime:'DD/MM/YYYY-HH:MM',
    taskType:'Task Type',
    selectTaskType:'Select Task Type',
    prospectOwener : 'Prospect Owner',
    selectprospectOwener : 'Select Prospect Owner',
    campaignId : 'Campaingn Id',
    selectcampaignId : 'Select campaingn Id',

    //outcome: 'Outcome',

    placeholderTop: '55rem',
    placeHolderLeft: '25rem',
    updateactivity: "Update Activity",
    outcome: 'Outcome',
    reviewRemark:'Review remark',
    anandMishra: 'Anand Mishra(60020)',
    yogeshDhayfule: 'Yogesh Dhayafule(70008)',
    hours0: 0,
    hours4: 4,
    enterReviewRemark:'Enter Review remark',






    privilege:'Privilege',
    preferred:'Preferred',
    hni:'HNI',
    products:'Products',
    actionType:'Action Type',
    selectactionType:'Select Action Type',
    invitee:'Invitee',
    activityStatus:'Activity Status : ',
    selectInvitee:'Select Invitee',
    selecttActivityStatus:'Select activity Status',
    selectAll:'Select All',
    phoneCall:'Phone Call',
    meeting:'Meeting',
    anandSharma:'Anand Sharma',
    amolMul:'Amul Mul chandrakant',
    dixon:'Dixon Dsouuza',
    activitydetails : 'Activity Details', 
    edit :  "Edit",
    leadcreatedon : "Lead Created on",
    activitydate : "10 May 2023",
    ActionType : "Action Type",
    LeadorClient : "Lead or Client ",
    ScheduleDate  : "Schedule Date",
    AssignedTo : "Assigned To",
    ActivityStatus :  "Activity Status",
    ActivityCreatedDate : "Activity Created Date",
    ProspectID : "Prospect ID",
    scheduletime : "30 May 2023",
    Rajeshsharma : 'RajeshSharma ,',
    held : 'Held',
    updatedDate : 'Updated Date',
    duration : "Duration",
    date18May2023 : '18 May 2023',
    Dtime : "00:15",
    Dtime245 : "02:45",
    Dtime134 : "01:34",
    historytext : "Lorem ipsum dolor sit amet, consectetur adipis cing elit. Sed metus nunc, accumsan ultricies orci eget, maximus tristique leo.",

    // Sign in screen
    placeHolderEmployeeID: 'Employee ID',
    placeHolderPassword: 'Password',
    signinHeaderText: 'Sign In With Your Employee ID',
    forgotPassword: 'Forgot Your Password ?',
    invalidPassword: 'Enter Correct Password',
    invalidEmployeeID: 'Enter Correct Employee ID',
    signin: 'SIGN IN',
    // Forget Password screen
    employeeID: "Employee ID",
    enteremployeeID: "Enter Employee ID",
    sendOTP: "Choose option to send OTP",
    getOTP: "Get OTP",



    //oppertunities screen
    searchOppertunities: "Search by Prospect ID/ Name /Mobile no",
    ratio: "1.40/80.60",
    revenu: "Rev./AUM(In Lac)",
    targateDateLabel: "Close Target Date:",
    targateDate: "05 Jun 23",
    invtAmount: "Invt.Amnt",
    invtAmounts: "20,00",
    productTypeLabel: "Product Type",
    productTypes: "Insurance",
    opportunityStageLabel: "Opportunity Stage",
    opportunityStage: "Closure",
    probabilityLabel: "Probability/Tagging",
    probabilitys: "50%/Privilege",
    fiscalPeriodLabel: "Fiscal Period",
    fiscalPeriod: "FY 21-22",
    history: "History",
    assignedLabel: "Assigned",
    assigned: "Anand Mishra",

    assignedName: "Anand Mishra",
    call: "call(7875876332)",
    calls: "7875876332",
    message: "Message",
    addActivity: "Add Activity",
    editOpportunity: "Edit Opportunity",
    addOpportunity: "Add Opportunity",



    /////
    ///Oppertunity Filter
    filter: "Filter",
    productType: "Product Type",
    oppertunityStage: "Oppertunity Stage",
    probability: "Probability",
    //iscalPeriod: "Fiscal Period",
    assignedTo: "Assigned To",
    selectproductType: "Select Product Type",
    selectOppertunityStage: "Select Oppertunity Stage",
    selectProbability: "Select Probability",
    selectFiscalPeriod: "Select Fiscal Period",
    selectAssignedTo: "Select Assigned To",
    placeHolderSearchProductType: 'Search product type',
    listofProductType: "List of product type",
    placeHolderSearchAssignedTo: 'Search assigned to',
    listofAssignedTo: "List of assigned to",
    placeHolderSearchFiscalPeriod: 'Search fiscal period',
    listofFiscalPeriod: "List of fiscal period",
    placeHolderSearchProbability: 'Search probability',
    listofProbability: "List of probability",
    placeHolderSearchOppertunityStage: 'Search oppertunity stage',
    listofOppertunityStage: "List of oppertunity stage",
    apply: "Apply",
    lastCreated: "Last Created On",
    created: "Created",
    ARCARESCodeLabel: "ARCCC/ ARCARES Code",
    clientCodeLabel: "Client Code",
    ARCARESCode: "223462588",
    clientCode: "E97XXX",
    revenuePotential: "Potential Revenue",
    aum: "Potential AUM",
    invtAmountLabel: "Investment Amount",
    tagging: "Tagging",
    updateDateTimeLabel: "Update Date Time",
    updateDateTime: "23-24 05 Jun 2023, 10:14 AM",
    email: "nagaart@gmail.com",
    ////// History screen
    completed: "Completed",
    targateDateTime: "Target Date Time",
    etfBond: "ETF Bond",
    clientTypeBadge1: 'HNI',
    clientTypeBadge2: 'Retail',
    clientTypeBadge3: 'Preferred',

    //////Add Opportunity
    addSearch: "Search by Prospect ID/Name ",
    leadid: 'Lead id',
    createdBy: 'Created By',
    product: 'Product',
    selectProductLabel: 'Select Product',
    placeHolderSearchProduct: 'Search product',
    listofProduct: "List of product",
    stage: 'Stage',
    selectStageLabel: 'Select Stage',
    placeHolderSearchStage: 'Search stage',
    listofStage: "List of stage",
    enterInvestmantAmount: 'Enter Investmant Amount',
    datePicker: 'DD/MM/YYYY',
    targateTime: 'Close Target Date & Time',
    enterAssigned: 'Employee Name (Code)',
    potential: 'Potential AUM',
    expectedRevenue: 'Expected Revenue',
    enterExpectedRevenue: 'Enter Expected Revenue',
    enterProbability: "Select probability",
    enterFiscalPeriod: 'Select Fiscal Period',
    enterPanCard: 'Enter Pan no',
    panCard: 'Pan Card',
    saveActivity: 'Save Activity',
    newLeads: 'New Leads',
    newClients: 'New Clients',
    searchAddOppertunities: "Search by Prospect ID/Name",
    //////
    // home: "home",
    // search: 'search',
    // dashboard: 'Dashboard',
    // person: 'Client',
    // monitorDashboard: 'monitor-dashboard',
    // userPlus: 'user-plus',
    // userCheck: 'user-check',
    // note: "note",
    // addCircle: 'add-circle',
    // leadClient: 'Lead/Client',
    // oppertunities: 'Oppertunities',
    // activity: 'Activity',
    // closeCircleSharp: 'close-circle-sharp',
    // bold: 'bold',
    // left: 'left',
    // right: 'right',
    // navText: 'FY 2022-23',
    // center: 'center',


    // home: "home",
    // search: 'search',
    // dashboard: 'Dashboard',
    // //person: 'client',
    // monitorDashboard: 'monitor-dashboard',
    // userPlus: 'user-plus',
    // userCheck: 'user-check',
    // note: "note",
    // addCircle: 'add-circle',
    // leadClient: 'Lead/Client',
    // oppertunities: 'Oppertunities',
    // activity: 'Activity',
    // closeCircleSharp: 'close-circle-sharp',
    // bold: 'bold',
    // left: 'left',
    // right: 'right',
    // navText: 'FY 2022-23',
    // center: 'center',

    home:"home",
    search:'search',
    dashboard:'Dashboard',
    person:'Client',
    monitorDashboard:'monitor-dashboard',
    userPlus:'user-plus',
    userCheck:'user-check',
    note:"note",
    addCircle:'add-circle',
    leadClient:'Lead/Client',
    oppertunities:'Oppertunities',
    activity:'Activity',
    closeCircleSharp:'close-circle-sharp',
    bold:'bold',
    left:'left',
    right:'right',
    navText:'FY 2022-23',
    center:'center',
    schedule: 'schedule',
    scheduleDateTime: "14 Apr 23 - Today",
    baveshKapsadia: "Bavesh Kapsadia",
    nagadharBandi: "Nagadhar Bandi",
    smithaIyar: "Smitha Iyar",
    schedule: 'schedule',
    scheduleDateTime: "14 Apr 23 - Today",
    //baveshKapsadia: "Bavesh Kapsadia",
    nagadharBandi: "Nagadhar Bandi",
    smithaIyar: "Smitha Iyar",

    //Dashboard screen 
    leads: "Leads",
    generatedValue: "48",
    convartedValue: "14",
    generated: "Generated",
    converted: "converted",
    targetvsAchievement: "Target vs Achievement",
    thismonth: "This Month",
    generatedcount: "48",
    convertedcount: "14",
    propspects: "Prospects",
    clients: "Clients",
    dormants: "Dormants",
    leadName1: "Revanath Bandi",
    leadName2: "Mohan Das Gupta",
    leadName3: "Kenisha Iyar",
    leadName4: "Hanshika Gajam",
    leadName5: "Siddhanth Jain",
    leadId1: "48006200",
    leadId2: "48006840",
    leadId4: "4800600",
    meetingdone1: "6",
    meetingdone2: "5",
    meetingdone3: "4",
    meetingdone4: "4",
    meetingdone5: "3",
    revenuAmount1: "1.40",
    revenuAmount2: "1.05",
    revenuAmount3: "0.90",
    revenuAmount4: "0.60",
    revenuAmount5: "0.30",
    revenuAmountInLac1: "80.60",
    revenuAmountInLac2: "70.20",
    revenuAmountInLac3: "55.85",
    revenuAmountInLac4: "30.40",
    revenuAmountInLac5: "22.30",
    name: "NAME",
    leadsId: "(Lead ID)",
    metting: "MEETINGS",
    done: "DONE",
    revenue: "P.REVENUE",
    amount: "/AUM(InLAC)",

    // revenuAmount1 : "1.40",
    // revenuAmount2 : "1.05",
    // revenuAmount3 : "0.90",
    // revenuAmount4 : "0.60",
    // revenuAmount5 : "0.30",
    // revenuAmountInLac1 : "80.60",
    // revenuAmountInLac2 : "70.20",
    // revenuAmountInLac3 : "55.85",
    // revenuAmountInLac4 : "30.40",
    // revenuAmountInLac5 : "22.30",
    // name : "NAME",
    // leadsId : "(Lead ID)",
    // metting : "MEETINGS",
    // done : "DONE",
    // revenue : "P.REVENUE",
    // amount : "/AUM(InLAC)",

    lead180: "180",
    lead10: "10",
    lead04: "04",
    lead140: "140",
    lead20: "20",
    lead06: "06",
    new: "New",
    Assigned: "Assigned",
    inprocess: "Inprocess",
    Converted: "Converted",
    Others: "Others",
    prospectSource: "Prospect Source:",
    assigned: "Assigned",
    Time: "10:00 AM - 10:45 AM",
    meeting: "Meeting",
    lastMeetingDateTime: "Last Meeting Outcome - Date and Time",
    mettingDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed metus nunc, accumsan ultricies orci eget",
    messageTime: "- 26 May 23, 10:00 - 10:45 AM",
    newAssignedleads: "New Assigned Leads",
    AndrewNolan: "Andrew Nolan",
    Referral: "Referral",
    Ageing: "Ageing:",
    days: "15 Days",
    marvinmckinney: "Marvin McKinney",
    //calls: "call",
    // call : "call",
    nonbusinessmeet: "Non Business Meet",
    oppertunities: "Opportunities",
    target: "Target",
    achievement: "Achievement",
    placeholder: "Search By Name. Mobile No",
    all: "ALL",
    clientcode: "(Client Code)",
    dormants: "DORMANTS",
    since: "SINCE",
    rameshRemma: "Ramesh Remma",
    sirishaJain: "Sirisha Jain",
    days15: "15 Days",
    days: "Days",
    days320: "320",
    days240: "240",
    days220: "220",
    days190: "190",
    days160: "160",
    days100: "100",
    days80: "80",
    days68: "68",
    days65: "65",
    days54: "54",
    days52: "52",
    days50: "50",
    days49: "49",
    clients480: "480",
    closed: "closed",
    createdcount: "28",
    closecount: "06",
    Noresultsfound: "No results found",
    Totalclient: "Total Client",

    lead180: "180",
    lead10: "10",
    lead04: "04",
    lead140: "140",
    lead20: "20",
    lead06: "06",
    new: "New",
    Assigned: "Assigned",
    inprocess: "Inprocess",
    Converted: "Converted",
    Others: "Others",
    prospectSource: "Prospect Source:",
    assigned: "Assigned",
    Time: "10:00 AM - 10:45 AM",
    meeting: "Meeting",
    lastMeetingDateTime: "Last Meeting Outcome - Date and Time",
    mettingDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed metus nunc, accumsan ultricies orci eget",
    messageTime: "- 26 May 23, 10:00 - 10:45 AM",
    newAssignedleads: "New Assigned Leads",
    AndrewNolan: "Andrew Nolan",
    Referral: "Referral",
    Ageing: "Ageing:",
    days: "15 Days",
    marvinmckinney: "Marvin McKinney",
    //calls: "call",
    nonbusinessmeet: "Non Business Meet",
    oppertunities: "Opportunities",
    target: "Target",
    achievement: "Achievement",
    placeholder: "Search By Name. Mobile No",
    all: "ALL",
    clientcode: "(Client Code)",
    dormants: "DORMANTS",
    since: "SINCE",
    rameshRemma: "Ramesh Remma",
    sirishaJain: "Sirisha Jain",
    days15: "15 Days",
    days: "Days",
    days320: "320",
    days240: "240",
    days220: "220",
    days190: "190",
    days160: "160",
    days100: "100",
    days80: "80",
    days68: "68",
    days65: "65",
    days54: "54",
    days52: "52",
    days50: "50",
    days49: "49",
    clients480: "480",
    closed: "closed",
    createdcount: "28",
    closecount: "06",
    Noresultsfound: "No results found",
    Totalclient: "Total Client",

    // Forget Password Otp screen
    enterOtp: "Enter OTP",
    verifyOTP: "Verify OTP",
    otpExpire: "OTP will Expire by",
    receiveOTP: "Didn't receive OTP?",
    resendOTP: "Resend OTP",


    //Set Password screen
    newPassword: "New Password",
    enterNewPassword: "Enter New Password",
    enterConfirmPassword: "Enter Confirm New Password",
    confirmPassword: "Confirm New Password",
    setNewPassword: "Set New Password",
    loginNow: "Login Now",

    //Add Lead Screen
    save: "Save",
    addLead1: "Add Lead 1/4",
    prospectDetails: "Prospect Details",
    clientType: "Client Type",
    firstName: "First Name",
    lastName: "Last Name",
    mobileNo: "Mobile No",
    alternateNo: "Alternate No. (Optional)",
    emailID: "Email ID",
    businessProfession: " Business & Profession",
    potentialRevenue: "Potential Revenue (Optional)",
    potentialAUM: "Potential AUM (Optional)",
    productType: "Product Type",
    enterFirstName: "Enter Name",
    enterLastName: "Enter Last Name",
    enterMobileNo: "Enter Mobile No",
    enterAlternateNo: "Alternate No",
    enterEmailID: "Enter Email ID",
    enterBusinessProfession: "Enter Business & Profession",
    enterPotentialRevenue: "Enter Potential Revenue",
    enterPotentialAUM: "Enter Potential AUM",
    broking: "Broking",
    nonBroking: "Non - Broking",
    saveNext: "Save & Next",
    invalidName: "Enter Correct Name,Numbers are not allowed",
    invalidMobileNo: "Enter Correct Mobile Number",
    matchPassword: "Passwords do not match",

    //Add Address
    addLead2: "Add Lead 2/4",
    addressInformation: "Address Information",
    address1: "Address 1",
    address: "Address",
    enterAddress: "Enter Address",
    pincode: "Pincode",
    invalidPincode: "Enter Correct Pincode",
    enterPostalCode: "Enter Postal Code",
    country: "Country",
    selectCountry: "Select Country",
    state: "State / Province",
    selectState: "Select State/Province",
    city: "City",
    selectCity: "Select City",
    addOneMoreAddress: "Add one more address",
    previous: "Previous",
    next: "Next",

    // Tracking Details
    addLead3: "Add Lead 3/4",
    trackingDetails: "Tracking Details",
    prospectSource: "Prospect Source",
    selectProspectSource: "Select Prospect Source",
    assignedToOptional: "Assigned To (Optional)",
    prospectStatus: "Prospect Status",
    prospectStage: "Prospect Stage",
    selectProspectStage: "Select Prospect Stage",
    prospectPriority: "Prospect Priority",
    selectProspectPriority: "Select Prospect Priority",
    employeeNameCode: "Employee Name (Code)",

    //Other Details
    addLead4: "Add Lead 4/4",
    otherDetails: "Other Details",
    addNotes: "Add Notes",
    addAttachment: "Add Attachment",
    plusCircleIcon: "plus-circle",

    //Add Notes
    addNotes: "Add Notes",
    subject: "Subject",
    enterSubject: "Enter Subject",
    description: "Description",
    addDescription: "Add Description",
    setReminder: "Set Reminder",
    setPriority: "Set Priority",
    selectPriority: "Select Priority",
    reminderDateTime: "Reminder Date & Time",
    dobPlaceHolder: "DD/MM/YYYY - HH:MM",
    addNotes: "Add Notes",
    //Calender
    selectDateTime: "Select Date & Time",
    hours: "Hours",
    minutes: "Minutes",
    am: "AM",
    reset: "Reset",
    done: "Done",

    // Notes card
    notes: "Notes",

    //Add Attachment
    gallery: "Gallery",
    takePhoto: "take Photo",
    upload: "Upload",
    selectFrom: "Select From",
    remove: "Remove",

    // Font Size
    s: '10rem',
    ss: '11rem',
    xs: '12rem',
    xss: '13rem',
    sm: '14rem',
    xsm: '15rem',
    md: '16rem',
    headerSize: "18rem",
    lg: '20rem',
    xl: '24rem',
    xxl: '25rem',
    xxxl: '30rem',
    //===============

    borderWidthSize: '1rem',
    borderWidthSize2: "2rem",

    textBoxHeight: '50rem',
    headerHeight: '60rem',
    scheduleBarHeight: '60rem',
    searchBarHeight: '70rem',
    propspectsHeight: "90rem",
    cardHeight: '100rem',
    historyCardHeight : '150rem',
    targetViewHeight: 150,
    cardviewHeight: '180rem',
    containerHeight: 100,
    leadtitlewidth: 140,
    leagendwidth: 10,
    leagendHeight: 10,
    lineHeight: 1,
    cardDivder: -90,
    propspectsHeight: "90rem",
    cardHeight: '100rem',

    cardviewHeight: '180rem',



    elavation5: '5rem',
    elavation8: '8rem',
    elavation10: '10rem',
    zero: 0,

    borderRadiusXS: '1rem',
    borderRadiusSM: '2rem',
    borderRadiusMD: '3rem',
    borderRadiusLG: '5rem',
    borderRadiusXL: '8rem',
    borderRadiusXXL: '10rem',
    borderRadius25: '25rem',
    borderRadius50: '50rem',
    /*padding**/
    p0: "0rem",
    p0_5: "0.5rem",
    p1: "1rem",
    p1_2: '1.2rem',
    p1_4: '1.4rem',
    p1_5: "1.5rem",
    p1_8: '1.8rem',
    p2: "2rem",
    p2_5: "2.5rem",
    p3: "3rem",
    p3_5: "3.5rem",
    p4: "4rem",
    p4_5: "4.5rem",
    p5: "5rem",
    p6: "6rem",
    p7: "7rem",
    p8: "8rem",
    p9: "9rem",
    p10: "10rem",
    p11: "10.72rem",
    p12: "12rem",
    p14: "14rem",
    p15: "15rem",
    p16: "16rem",
    p18: "18rem",
    p20: "20rem",
    p22: "22rem",
    p24: "24rem",
    p32: "32rem",
    p30: "30rem",
    p36: "36rem",
    p40: "40rem",
    p48: "48rem",
    p50: "50rem",
    p52: "52rem",
    p72: "72rem",
    p75: '75rem',
    p80: "80rem",
    //===============

    /*margin*/
    mauto: "auto",
    m0: "0rem",
    m0_5: "0.5rem",
    m1: "1rem",
    m1_5: "1.5rem",
    m2: "2rem",
    m2_5: "2.5rem",
    m3: "3rem",
    m3_5: "3.5rem",
    m4: "4rem",
    m4_5: "4.5rem",
    m5: "5rem",
    m6: "6rem",
    m7: "7rem",
    m8: "8rem",
    m10: "10rem",
    m12: "12rem",
    m15: "15rem",
    m16: "16rem",
    m18: "18rem",
    m24: "24rem",
    m28: "28rem",
    m34: "34rem",
    m40: "40rem",
    m48: "48rem",
    m58: "58rem",
    m80: "80rem",
    m94: "94rem",

    //===============

    // Width
    width10: "10%",
    width20: '20%',
    width40: '40%',
    width50: '50%',
    width60: '60%',
    width80: '80%',
    width90: '90%',
    width100: '100%',
    width120: '120%',
    width200: '200%',
    width230: '230%',
    width330: '330%',
    width320: '320%',
    //===============

    // Percentage
    per0_1: '0.1%',
    per0_2: '0.2%',
    per0_3: '0.3%',
    per0_4: '0.4%',
    per0_5: '0.5%',
    per0_6: '0.6%',
    per0_8: '0.8%',
    per1: '1%',
    per1_2: '1.2%',
    per1_3: '1.3%',
    per1_4: '1.4%',
    per1_5: '1.5%',
    per1_6: '1.6%',
    per1_8: '1.8%',
    per2: '2%',
    per2_5: '2.5%',
    per3: '3%',
    per3_5: '3.5%',
    per4: '4%',
    per4_5: '4.5%',
    per5: '5%',
    per10: '10%',
    per30: '30%',
    per92: '92%',
    //===============

    //piechartValue
    radius: 50,
    innerRadius: 35,
    percentagevalue25: 25,
    percentageValue10: 10,
    percentageValue40: 40,
    percentageValue8: 8,
    percentageValue42: 42,
    innerRadius: 35,
    percentagevalue25: 25,
    percentageValue10: 10,
    percentageValue40: 40,
    //===============

    //heights
    containerHeight: 100,
    leadtitlewidth: 140,
    leadcardHeight: 120,
    leagendwidth: 10,
    leagendHeight: 10,
    lineHeight: 0.3,
    cardDivder: -90,
    leadclientcard: -60,
    targetViewHeight: 150,
    leadheight: 110,
    iconleft: -40,
    pieChartCard: 340,
    //width70: 70,
    width14: 14,
    mettingCard: 26,
    lineHeight20: 20,
    cardHeight160: 160,
    leadtitlewidth: 140,
    leadcardHeight: 120,
    leagendwidth: 10,
    leagendHeight: 10,
    lineHeight: 0.3,
    cardDivder: -90,
    targetViewHeight: 150,
    //================

    //opacity
    opacity0_5: 0.5,
    opacity0_6: 0.6,
    opacity0_7: 0.7,
    //===============

}